# Generated by Django 5.0.7 on 2025-08-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attendancerecord_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='reg_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='subject',
        ),
    ]
